export const SEED_FAQS = [
  {
    category: 'Kiến thức niềng răng',
    question: 'Niềng răng mất bao lâu?',
    answer: 'Thời gian niềng khay trong suốt Dr.Wondersmile từ 6 tháng đến 12 tháng tùy tình trạng. Răng nhẹ (thưa, niềng lại) dưới 6 tháng. Răng khó (hô, móm, khấp khểnh) từ 10-12 tháng.',
    related_questions: ['Bao lâu niềng xong?', 'Niềng mấy tháng?', 'Thời gian niềng bao lâu?'],
    keywords: ['thời gian', 'bao lâu', 'mấy tháng'],
  },
  {
    category: 'Báo giá & Chi phí',
    question: 'Chi phí niềng răng bao nhiêu?',
    answer: 'Chi phí niềng khay Dr.Wondersmile có 2 gói:\n- Gói cơ bản: 33 triệu (răng nhẹ, dưới 6 tháng)\n- Gói chuyên sâu: 65 triệu ƯU ĐÃI còn 45 triệu (răng khó, trên 6 tháng)\nTrọn gói bao gồm khay niềng, mài kẽ, gắn attachment, nhổ răng (nếu có), vệ sinh răng.',
    related_questions: ['Giá niềng bao nhiêu?', 'Bao nhiêu tiền?', 'Mắc không?'],
    keywords: ['giá', 'chi phí', 'bao nhiêu', 'tiền'],
  },
  {
    category: 'Kiến thức niềng răng',
    question: 'Niềng khay trong suốt có đau không?',
    answer: 'Niềng khay trong suốt HẠN CHẾ ĐAU, không cợm cấn khó chịu, không nhiệt lỡ miệng hay hôi miệng như niềng mắc cài. Những ngày đầu đeo khay mới có thể hơi ê nhẹ do răng bắt đầu di chuyển, sau 2-3 ngày sẽ quen.',
    related_questions: ['Có đau không?', 'Niềng có khó chịu không?', 'Đeo khay có đau không?'],
    keywords: ['đau', 'khó chịu', 'ê răng'],
  },
  {
    category: 'Kiến thức niềng răng',
    question: 'Niềng khay ban đêm khác gì ban ngày?',
    answer: 'Niềng khay ban ngày đeo ít nhất 20 tiếng/ngày. Niềng khay ban đêm chỉ đeo 10 tiếng (buổi tối), ban ngày không cần đeo. Khay đêm thời gian niềng dài hơn 1-2 tháng so với khay ngày. Phù hợp người bận công việc giao tiếp nhiều.',
    related_questions: ['Khay ban đêm là gì?', 'Đeo bao nhiêu tiếng?', 'Ngày đeo mấy tiếng?'],
    keywords: ['ban đêm', 'ban ngày', 'tiếng', 'đeo'],
  },
  {
    category: 'Kiến thức niềng răng',
    question: 'Có cần nhổ răng khi niềng không?',
    answer: 'Niềng khay Dr.Wondersmile HẠN CHẾ NHỔ RĂNG, ưu tiên BẢO TỒN RĂNG THẬT ở mức độ tối đa. Tùy tình trạng răng, bác sĩ sẽ đánh giá khi lên phác đồ 3D. Đa số trường hợp không cần nhổ.',
    related_questions: ['Phải nhổ răng không?', 'Có giữ răng không?', 'Có mài răng không?'],
    keywords: ['nhổ răng', 'bảo tồn', 'giữ răng'],
  },
  {
    category: 'Báo giá & Chi phí',
    question: 'Có trả góp được không?',
    answer: 'Có hỗ trợ trả góp 0% lãi suất qua thẻ tín dụng:\n- Thời gian trả góp từ 6-12 tháng\n- Thanh toán trước 30-50%\n- Phần còn lại góp hàng tháng\nHỗ trợ thanh toán trực tiếp hoặc qua thẻ.',
    related_questions: ['Trả góp thế nào?', 'Đóng 1 lần hay chia ra?', 'Lãi suất bao nhiêu?'],
    keywords: ['trả góp', 'chia nhỏ', 'lãi suất', 'thanh toán'],
  },
  {
    category: 'Thông tin nha khoa',
    question: 'Nha khoa có ở đâu?',
    answer: 'Trụ sở chính:\n- HCM: 77C Bùi Thị Xuân, Q1\n- Hà Nội: 99 Giải Phóng, Hai Bà Trưng\n\nChi nhánh liên kết: Đà Nẵng, Biên Hòa, Dĩ An - Bình Dương, Đồng Xoài - Bình Phước, Vĩnh Long.',
    related_questions: ['Địa chỉ ở đâu?', 'Có chi nhánh nào?', 'HCM ở đâu?'],
    keywords: ['địa chỉ', 'ở đâu', 'chi nhánh'],
  },
  {
    category: 'Kiến thức niềng răng',
    question: 'Bảo hành như thế nào?',
    answer: 'Dr.Wondersmile cam kết niềng THÀNH CÔNG 100% bằng hợp đồng văn bản:\n- Bảo hộ rủi ro trong quá trình niềng\n- Nếu kết quả không đạt so với phác đồ, bảo hành in khay tinh chỉnh MIỄN PHÍ 100%\n- Mọi cam kết đều rõ ràng trên hợp đồng.',
    related_questions: ['Cam kết gì?', 'Nếu không đạt thì sao?', 'Có hoàn tiền không?'],
    keywords: ['bảo hành', 'cam kết', 'thành công', 'hợp đồng'],
  },
  {
    category: 'Thông tin nha khoa',
    question: 'Thăm khám có mất phí không?',
    answer: 'Thăm khám tư vấn hoàn toàn MIỄN PHÍ. Thời gian khoảng 30 phút. Lịch thăm khám từ 9h đến 18h30 tất cả các ngày trong tuần (làm việc xuyên trưa, kể cả T7-CN).',
    related_questions: ['Khám miễn phí không?', 'Tư vấn có mất tiền không?', 'Đến tư vấn mất phí gì?'],
    keywords: ['miễn phí', 'phí khám', 'tư vấn'],
  },
  {
    category: 'Kiến thức niềng răng',
    question: 'Hãng khay Dr.Wondersmile là gì?',
    answer: 'Dr.Wondersmile là hãng khay niềng trong suốt:\n- Nhà máy sản xuất tại Đức\n- Có mặt 17 nước, 400.000+ case thành công\n- Chất liệu Zendura FLX 3 lớp, không chứa BPA\n- Phác đồ 100% do chuyên gia tiến sĩ nước ngoài lên\n- Chứng nhận FDA Hoa Kỳ\n- Cam kết 1:1 bằng hợp đồng',
    related_questions: ['Khay niềng hãng nào?', 'Wondersmile là gì?', 'Xuất xứ khay ở đâu?'],
    keywords: ['wondersmile', 'hãng khay', 'xuất xứ', 'đức'],
  },
];
