export const SEED_PHRASES = [
  // ===== QUY TRÌNH TƯ VẤN =====
  {
    category: 'Quy trình tư vấn',
    intent: 'chao_hoi',
    user_message: 'Xin chào',
    bot_response: 'Niềng răng trong suốt Dr.Wondersmile xin chào!',
    keywords: ['chào', 'hello', 'hi'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'hoi_tinh_trang',
    user_message: 'Tôi muốn niềng răng',
    bot_response: 'Chị chia sẻ giúp em về tình trạng răng đang gặp phải và mong muốn khi niềng. Để nha khoa tư vấn chi tiết về PHƯƠNG ÁN và CHI PHÍ trước khi chị đến thăm khám trực tiếp?',
    keywords: ['niềng răng', 'muốn niềng', 'tình trạng'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'hoi_tinh_trang_2',
    user_message: 'Mình muốn tư vấn niềng răng',
    bot_response: 'Răng của mình đang nằm trong trường hợp nào dưới đây:\n+ Răng mọc xô lệch, chen chúc\n+ Răng hô\n+ Răng móm\n+ Răng thưa\n+ Đã niềng rồi nhưng muốn niềng lại\n+ Đang đeo niềng mắc cài muốn đổi qua khay\nMình chia sẻ để em hỗ trợ thông tin trước khi mình ghé nha khoa thăm khám ạ?',
    keywords: ['tư vấn', 'niềng', 'thông tin'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'xin_sdt',
    user_message: 'Cho tôi thông tin thêm',
    bot_response: 'Em nhận thông tin của chị ạ. Chị gửi em số điện thoại bên em liên hệ tư vấn kĩ lưỡng nhanh chóng cho mình chị nha. Hay chị muốn hỗ trợ qua tin nhắn ạ?',
    keywords: ['số điện thoại', 'liên hệ', 'sdt'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'danh_gia_rang_kho',
    user_message: 'Răng tôi bị khấp khểnh nhiều',
    bot_response: 'Tình trạng răng khấp khểnh thì hoàn toàn khắc phục được 100% khi niềng khay trong suốt bên em.',
    keywords: ['khấp khểnh', 'lộn xộn', 'hô', 'móm'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'danh_gia_rang_nhe',
    user_message: 'Răng tôi bị thưa nhẹ',
    bot_response: 'Tình trạng răng thưa ở mức độ nhẹ của mình thì hoàn toàn khắc phục được khi niềng khay ạ.',
    keywords: ['thưa', 'nhẹ', 'niềng lại'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'danh_gia_nieng_lai',
    user_message: 'Tôi đã niềng rồi muốn niềng lại',
    bot_response: 'Răng mình từng niềng rồi giờ mình niềng lại bằng khay thì hoàn toàn khắc phục được. Tùy vào tình trạng răng chạy thì khi lên phác đồ sẽ có kết quả điều trị.',
    keywords: ['niềng lại', 'đã niềng', 'niềng trước'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'gui_hinh_ket_qua',
    user_message: 'Niềng có thay đổi nhiều không?',
    bot_response: 'Hình ảnh khách hàng niềng khay bên em. Niềng răng giúp răng đều mà sẽ còn giúp thay đổi gương mặt cân đối, tránh tình trạng răng hư hại về sau. Ngoài ra góc niềng của mình và nụ cười sẽ thay đổi sau niềng.',
    keywords: ['kết quả', 'thay đổi', 'hiệu quả'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'hoi_lich_hen',
    user_message: 'Khi nào tôi có thể đến khám?',
    bot_response: 'Không biết hôm nay mình ghé bên em thăm khám tiện không ạ?',
    keywords: ['lịch hẹn', 'thăm khám', 'đặt hẹn', 'khi nào'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'xin_thong_tin_dat_hen',
    user_message: 'Tôi muốn đặt lịch hẹn',
    bot_response: 'Chị gửi em xin SỐ ĐIỆN THOẠI và tên để em tạo lịch hẹn trên hệ thống nha khoa bên em ạ?',
    keywords: ['đặt lịch', 'đặt hẹn', 'book'],
  },
  {
    category: 'Quy trình tư vấn',
    intent: 'tham_kham_mien_phi',
    user_message: 'Thăm khám có mất phí không?',
    bot_response: 'Thăm khám tư vấn MIỄN PHÍ, thời gian khoảng 30p. Nhận lịch thăm khám từ 9h -> 18h30 tất cả các ngày trong tuần (làm việc xuyên trưa).',
    keywords: ['miễn phí', 'phí thăm khám', 'mất phí'],
  },
];
