export const SEED_SCENARIOS = [
  {
    category: 'Quy trình tư vấn',
    title: 'Khách hỏi giá ngay từ đầu',
    description: 'Khách hàng hỏi giá mà chưa chia sẻ tình trạng răng',
    trigger_condition: 'Khi khách hỏi giá ngay từ đầu cuộc hội thoại',
    severity: 'normal',
    resolution_guide: 'Báo giá 2 gói niềng rồi xin tình trạng răng của khách hàng',
    conversation_flow: [
      { role: 'user', message: 'Niềng răng bao nhiêu tiền?' },
      { role: 'bot', message: 'Chi phí niềng khay trong suốt Dr.Wondersmile có 2 gói:\n- Gói niềng cơ bản 33 triệu\n- Gói niềng chuyên sâu 65 triệu ƯU ĐÃI còn 45 triệu\nMình chia sẻ giúp em tình trạng răng đang gặp phải để em tư vấn gói phù hợp ạ?' },
      { role: 'user', message: 'Răng tôi bị hô' },
      { role: 'bot', message: 'Tình trạng răng hô thì hoàn toàn khắc phục được 100% khi niềng khay trong suốt bên em. Tình trạng răng của mình niềng khoảng 10-12 tháng, chi phí niềng trọn gói ở gói 45 triệu ạ.' },
    ],
    tags: ['giá', 'báo giá', 'đầu cuộc hội thoại'],
  },
  {
    category: 'Tình huống xử lý',
    title: 'Khách ở tỉnh muốn niềng',
    description: 'Khách ở xa, lo ngại về tái khám',
    trigger_condition: 'Khi khách báo ở tỉnh hoặc ở xa nha khoa',
    severity: 'normal',
    resolution_guide: 'Giải thích niềng khay linh động, có app theo dõi, 3-4 tháng tái khám 1 lần. Hỏi có hay lên HCM không.',
    conversation_flow: [
      { role: 'user', message: 'Tôi ở Cần Thơ, niềng được không?' },
      { role: 'bot', message: 'Mình ở tỉnh thì vẫn có thể ghé bên em niềng vẫn được ạ. Vì niềng khay trong suốt mình sẽ linh động đeo niềng tại nhà theo dõi qua app. Tầm 3-4 tháng mới tái khám sẽ tiết kiệm khoảng thời gian di chuyển. Không biết mình có hay lên HCM không ạ?' },
      { role: 'user', message: 'Thỉnh thoảng tôi lên' },
      { role: 'bot', message: 'Vậy tiện quá ạ! Mình ghé bên em thăm khám trước để lên phác đồ 3D, sau đó về nhà đeo khay theo hướng dẫn. Bên em cũng có hỗ trợ đặt xe đưa đón miễn phí nếu mình không tiện di chuyển ạ.' },
    ],
    tags: ['ở tỉnh', 'xa', 'tái khám'],
  },
  {
    category: 'Tình huống xử lý',
    title: 'Khách phàn nàn về giá cao',
    description: 'Khách so sánh giá hoặc nói đắt',
    trigger_condition: 'Khi khách nói giá đắt, so sánh với nơi khác',
    severity: 'high',
    resolution_guide: 'Nhấn mạnh giá trị: hãng khay Đức, bảo hành 100%, bác sĩ nước ngoài lên phác đồ, trả góp 0%',
    conversation_flow: [
      { role: 'user', message: 'Sao đắt vậy? Chỗ khác có 20 triệu thôi' },
      { role: 'bot', message: 'Em hiểu mình so sánh giá ạ. Bên em là hãng khay Dr.Wondersmile nhập khẩu từ Đức, có mặt 17 nước trên thế giới với hơn 400.000 case thành công. Phác đồ do 100% chuyên gia tiến sĩ nước ngoài lên, được FDA chứng nhận. Quan trọng là CAM KẾT BẢO HÀNH 100% bằng hợp đồng văn bản.' },
      { role: 'user', message: 'Nhưng vẫn đắt' },
      { role: 'bot', message: 'Bên em có hỗ trợ trả góp 0% lãi suất qua thẻ tín dụng, thanh toán chỉ từ 30-50% trước. Phần còn lại góp hàng tháng từ 6-12 tháng. Mình ghé thăm khám MIỄN PHÍ xem phác đồ 3D trước rồi quyết định cũng được ạ.' },
    ],
    tags: ['đắt', 'so sánh giá', 'phàn nàn'],
  },
  {
    category: 'Chăm sóc khách hàng',
    title: 'Khách không trả lời tin nhắn',
    description: 'Follow up khi khách im lặng',
    trigger_condition: 'Khi khách hàng không phản hồi sau khi xin tình trạng',
    severity: 'low',
    resolution_guide: 'Gửi CSKH lần 1 sau 24h, lần 2 sau 48h, lần 3 sau 72h với mẫu câu khác nhau',
    conversation_flow: [
      { role: 'bot', message: 'Chị ơi mình quan tâm đến niềng khay trong suốt, chị cần em hỗ trợ thông tin gì để chị tìm hiểu ạ?' },
      { role: 'bot', message: 'Em thấy mình đang quan tâm đến niềng răng đã lâu, chị cần bên em cung cấp thêm thông tin gì để chị tiện tìm hiểu về niềng?' },
      { role: 'bot', message: 'Chị ơi không biết mình còn quan tâm đến niềng răng để cải thiện tình trạng của mình không ạ?' },
    ],
    tags: ['không trả lời', 'follow up', 'CSKH'],
  },
  {
    category: 'Quy trình tư vấn',
    title: 'Chốt lịch hẹn thành công',
    description: 'Quy trình xác nhận đặt hẹn',
    trigger_condition: 'Khi khách đồng ý đặt lịch hẹn thăm khám',
    severity: 'normal',
    resolution_guide: 'Xin tên + SĐT, xác nhận lịch hẹn, gửi thông tin địa chỉ',
    conversation_flow: [
      { role: 'user', message: 'OK mai tôi ghé được' },
      { role: 'bot', message: 'Chị gửi em xin SỐ ĐIỆN THOẠI và tên để em tạo lịch hẹn trên hệ thống nha khoa bên em ạ?' },
      { role: 'user', message: 'Nguyễn Thị A, 0901234567' },
      { role: 'bot', message: 'XÁC NHẬN ĐẶT HẸN THÀNH CÔNG TẠI DR.WONDERSMILE\nNgười Đăng Ký: Chị A\nSố Điện Thoại: 0901234567\nDịch Vụ: Niềng Răng Trong Suốt\n\nĐịa chỉ nha khoa: 77C Bùi Thị Xuân, Q1, HCM\nHẹn gặp chị tại nha khoa ạ!' },
    ],
    tags: ['đặt hẹn', 'chốt lịch', 'xác nhận'],
  },
];
